directory: "~/Downloads/"
colors:
  window_bg: "#282c34"
  base_text: "#c678dd"
  input_field_bg: "#363a42"
  input_field_fg: "#56b6c2"
  info_fg: "#61afef"
  feedback_fg: "#98c379"
  button_bg: "#e06c75"
  button_bg_hovered: "#d27f85"
  button_fg: "#282c34"
